// This file originates from the SatoshiLabs Trezor `common` repository at:
//   https://github.com/trezor/trezor-common/blob/master/protob/messages.proto
// dated 28.05.2019, commit 893fd219d4a01bcffa0cd9cfa631856371ec5aa9.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: messages.proto

package trezor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Mapping between TREZOR wire identifier (uint) and a protobuf message
type MessageType int32

const (
	// Management
	MessageType_MessageType_Initialize             MessageType = 0
	MessageType_MessageType_Ping                   MessageType = 1
	MessageType_MessageType_Success                MessageType = 2
	MessageType_MessageType_Failure                MessageType = 3
	MessageType_MessageType_ChangePin              MessageType = 4
	MessageType_MessageType_WipeDevice             MessageType = 5
	MessageType_MessageType_GetEntropy             MessageType = 9
	MessageType_MessageType_Entropy                MessageType = 10
	MessageType_MessageType_LoadDevice             MessageType = 13
	MessageType_MessageType_ResetDevice            MessageType = 14
	MessageType_MessageType_Features               MessageType = 17
	MessageType_MessageType_PinMatrixRequest       MessageType = 18
	MessageType_MessageType_PinMatrixAck           MessageType = 19
	MessageType_MessageType_Cancel                 MessageType = 20
	MessageType_MessageType_ClearSession           MessageType = 24
	MessageType_MessageType_ApplySettings          MessageType = 25
	MessageType_MessageType_ButtonRequest          MessageType = 26
	MessageType_MessageType_ButtonAck              MessageType = 27
	MessageType_MessageType_ApplyFlags             MessageType = 28
	MessageType_MessageType_BackupDevice           MessageType = 34
	MessageType_MessageType_EntropyRequest         MessageType = 35
	MessageType_MessageType_EntropyAck             MessageType = 36
	MessageType_MessageType_PassphraseRequest      MessageType = 41
	MessageType_MessageType_PassphraseAck          MessageType = 42
	MessageType_MessageType_PassphraseStateRequest MessageType = 77
	MessageType_MessageType_PassphraseStateAck     MessageType = 78
	MessageType_MessageType_RecoveryDevice         MessageType = 45
	MessageType_MessageType_WordRequest            MessageType = 46
	MessageType_MessageType_WordAck                MessageType = 47
	MessageType_MessageType_GetFeatures            MessageType = 55
	MessageType_MessageType_SetU2FCounter          MessageType = 63
	// Bootloader
	MessageType_MessageType_FirmwareErase   MessageType = 6
	MessageType_MessageType_FirmwareUpload  MessageType = 7
	MessageType_MessageType_FirmwareRequest MessageType = 8
	MessageType_MessageType_SelfTest        MessageType = 32
	// Bitcoin
	MessageType_MessageType_GetPublicKey     MessageType = 11
	MessageType_MessageType_PublicKey        MessageType = 12
	MessageType_MessageType_SignTx           MessageType = 15
	MessageType_MessageType_TxRequest        MessageType = 21
	MessageType_MessageType_TxAck            MessageType = 22
	MessageType_MessageType_GetAddress       MessageType = 29
	MessageType_MessageType_Address          MessageType = 30
	MessageType_MessageType_SignMessage      MessageType = 38
	MessageType_MessageType_VerifyMessage    MessageType = 39
	MessageType_MessageType_MessageSignature MessageType = 40
	// Crypto
	MessageType_MessageType_CipherKeyValue    MessageType = 23
	MessageType_MessageType_CipheredKeyValue  MessageType = 48
	MessageType_MessageType_SignIdentity      MessageType = 53
	MessageType_MessageType_SignedIdentity    MessageType = 54
	MessageType_MessageType_GetECDHSessionKey MessageType = 61
	MessageType_MessageType_ECDHSessionKey    MessageType = 62
	MessageType_MessageType_CosiCommit        MessageType = 71
	MessageType_MessageType_CosiCommitment    MessageType = 72
	MessageType_MessageType_CosiSign          MessageType = 73
	MessageType_MessageType_CosiSignature     MessageType = 74
	// Debug
	MessageType_MessageType_DebugLinkDecision    MessageType = 100
	MessageType_MessageType_DebugLinkGetState    MessageType = 101
	MessageType_MessageType_DebugLinkState       MessageType = 102
	MessageType_MessageType_DebugLinkStop        MessageType = 103
	MessageType_MessageType_DebugLinkLog         MessageType = 104
	MessageType_MessageType_DebugLinkMemoryRead  MessageType = 110
	MessageType_MessageType_DebugLinkMemory      MessageType = 111
	MessageType_MessageType_DebugLinkMemoryWrite MessageType = 112
	MessageType_MessageType_DebugLinkFlashErase  MessageType = 113
	// Ethereum
	MessageType_MessageType_EthereumGetPublicKey     MessageType = 450
	MessageType_MessageType_EthereumPublicKey        MessageType = 451
	MessageType_MessageType_EthereumGetAddress       MessageType = 56
	MessageType_MessageType_EthereumAddress          MessageType = 57
	MessageType_MessageType_EthereumSignTx           MessageType = 58
	MessageType_MessageType_EthereumTxRequest        MessageType = 59
	MessageType_MessageType_EthereumTxAck            MessageType = 60
	MessageType_MessageType_EthereumSignMessage      MessageType = 64
	MessageType_MessageType_EthereumVerifyMessage    MessageType = 65
	MessageType_MessageType_EthereumMessageSignature MessageType = 66
	// NEM
	MessageType_MessageType_NEMGetAddress       MessageType = 67
	MessageType_MessageType_NEMAddress          MessageType = 68
	MessageType_MessageType_NEMSignTx           MessageType = 69
	MessageType_MessageType_NEMSignedTx         MessageType = 70
	MessageType_MessageType_NEMDecryptMessage   MessageType = 75
	MessageType_MessageType_NEMDecryptedMessage MessageType = 76
	// Lisk
	MessageType_MessageType_LiskGetAddress       MessageType = 114
	MessageType_MessageType_LiskAddress          MessageType = 115
	MessageType_MessageType_LiskSignTx           MessageType = 116
	MessageType_MessageType_LiskSignedTx         MessageType = 117
	MessageType_MessageType_LiskSignMessage      MessageType = 118
	MessageType_MessageType_LiskMessageSignature MessageType = 119
	MessageType_MessageType_LiskVerifyMessage    MessageType = 120
	MessageType_MessageType_LiskGetPublicKey     MessageType = 121
	MessageType_MessageType_LiskPublicKey        MessageType = 122
	// Tezos
	MessageType_MessageType_TezosGetAddress   MessageType = 150
	MessageType_MessageType_TezosAddress      MessageType = 151
	MessageType_MessageType_TezosSignTx       MessageType = 152
	MessageType_MessageType_TezosSignedTx     MessageType = 153
	MessageType_MessageType_TezosGetPublicKey MessageType = 154
	MessageType_MessageType_TezosPublicKey    MessageType = 155
	// Stellar
	MessageType_MessageType_StellarSignTx               MessageType = 202
	MessageType_MessageType_StellarTxOpRequest          MessageType = 203
	MessageType_MessageType_StellarGetAddress           MessageType = 207
	MessageType_MessageType_StellarAddress              MessageType = 208
	MessageType_MessageType_StellarCreateAccountOp      MessageType = 210
	MessageType_MessageType_StellarPaymentOp            MessageType = 211
	MessageType_MessageType_StellarPathPaymentOp        MessageType = 212
	MessageType_MessageType_StellarManageOfferOp        MessageType = 213
	MessageType_MessageType_StellarCreatePassiveOfferOp MessageType = 214
	MessageType_MessageType_StellarSetOptionsOp         MessageType = 215
	MessageType_MessageType_StellarChangeTrustOp        MessageType = 216
	MessageType_MessageType_StellarAllowTrustOp         MessageType = 217
	MessageType_MessageType_StellarAccountMergeOp       MessageType = 218
	// omitted: StellarInflationOp is not a supported operation, would be 219
	MessageType_MessageType_StellarManageDataOp   MessageType = 220
	MessageType_MessageType_StellarBumpSequenceOp MessageType = 221
	MessageType_MessageType_StellarSignedTx       MessageType = 230
	// TRON
	MessageType_MessageType_TronGetAddress MessageType = 250
	MessageType_MessageType_TronAddress    MessageType = 251
	MessageType_MessageType_TronSignTx     MessageType = 252
	MessageType_MessageType_TronSignedTx   MessageType = 253
	// Cardano
	// dropped Sign/VerifyMessage ids 300-302
	MessageType_MessageType_CardanoSignTx       MessageType = 303
	MessageType_MessageType_CardanoTxRequest    MessageType = 304
	MessageType_MessageType_CardanoGetPublicKey MessageType = 305
	MessageType_MessageType_CardanoPublicKey    MessageType = 306
	MessageType_MessageType_CardanoGetAddress   MessageType = 307
	MessageType_MessageType_CardanoAddress      MessageType = 308
	MessageType_MessageType_CardanoTxAck        MessageType = 309
	MessageType_MessageType_CardanoSignedTx     MessageType = 310
	// Ontology
	MessageType_MessageType_OntologyGetAddress               MessageType = 350
	MessageType_MessageType_OntologyAddress                  MessageType = 351
	MessageType_MessageType_OntologyGetPublicKey             MessageType = 352
	MessageType_MessageType_OntologyPublicKey                MessageType = 353
	MessageType_MessageType_OntologySignTransfer             MessageType = 354
	MessageType_MessageType_OntologySignedTransfer           MessageType = 355
	MessageType_MessageType_OntologySignWithdrawOng          MessageType = 356
	MessageType_MessageType_OntologySignedWithdrawOng        MessageType = 357
	MessageType_MessageType_OntologySignOntIdRegister        MessageType = 358
	MessageType_MessageType_OntologySignedOntIdRegister      MessageType = 359
	MessageType_MessageType_OntologySignOntIdAddAttributes   MessageType = 360
	MessageType_MessageType_OntologySignedOntIdAddAttributes MessageType = 361
	// Ripple
	MessageType_MessageType_RippleGetAddress MessageType = 400
	MessageType_MessageType_RippleAddress    MessageType = 401
	MessageType_MessageType_RippleSignTx     MessageType = 402
	MessageType_MessageType_RippleSignedTx   MessageType = 403
	// Monero
	MessageType_MessageType_MoneroTransactionInitRequest              MessageType = 501
	MessageType_MessageType_MoneroTransactionInitAck                  MessageType = 502
	MessageType_MessageType_MoneroTransactionSetInputRequest          MessageType = 503
	MessageType_MessageType_MoneroTransactionSetInputAck              MessageType = 504
	MessageType_MessageType_MoneroTransactionInputsPermutationRequest MessageType = 505
	MessageType_MessageType_MoneroTransactionInputsPermutationAck     MessageType = 506
	MessageType_MessageType_MoneroTransactionInputViniRequest         MessageType = 507
	MessageType_MessageType_MoneroTransactionInputViniAck             MessageType = 508
	MessageType_MessageType_MoneroTransactionAllInputsSetRequest      MessageType = 509
	MessageType_MessageType_MoneroTransactionAllInputsSetAck          MessageType = 510
	MessageType_MessageType_MoneroTransactionSetOutputRequest         MessageType = 511
	MessageType_MessageType_MoneroTransactionSetOutputAck             MessageType = 512
	MessageType_MessageType_MoneroTransactionAllOutSetRequest         MessageType = 513
	MessageType_MessageType_MoneroTransactionAllOutSetAck             MessageType = 514
	MessageType_MessageType_MoneroTransactionSignInputRequest         MessageType = 515
	MessageType_MessageType_MoneroTransactionSignInputAck             MessageType = 516
	MessageType_MessageType_MoneroTransactionFinalRequest             MessageType = 517
	MessageType_MessageType_MoneroTransactionFinalAck                 MessageType = 518
	MessageType_MessageType_MoneroKeyImageExportInitRequest           MessageType = 530
	MessageType_MessageType_MoneroKeyImageExportInitAck               MessageType = 531
	MessageType_MessageType_MoneroKeyImageSyncStepRequest             MessageType = 532
	MessageType_MessageType_MoneroKeyImageSyncStepAck                 MessageType = 533
	MessageType_MessageType_MoneroKeyImageSyncFinalRequest            MessageType = 534
	MessageType_MessageType_MoneroKeyImageSyncFinalAck                MessageType = 535
	MessageType_MessageType_MoneroGetAddress                          MessageType = 540
	MessageType_MessageType_MoneroAddress                             MessageType = 541
	MessageType_MessageType_MoneroGetWatchKey                         MessageType = 542
	MessageType_MessageType_MoneroWatchKey                            MessageType = 543
	MessageType_MessageType_DebugMoneroDiagRequest                    MessageType = 546
	MessageType_MessageType_DebugMoneroDiagAck                        MessageType = 547
	MessageType_MessageType_MoneroGetTxKeyRequest                     MessageType = 550
	MessageType_MessageType_MoneroGetTxKeyAck                         MessageType = 551
	MessageType_MessageType_MoneroLiveRefreshStartRequest             MessageType = 552
	MessageType_MessageType_MoneroLiveRefreshStartAck                 MessageType = 553
	MessageType_MessageType_MoneroLiveRefreshStepRequest              MessageType = 554
	MessageType_MessageType_MoneroLiveRefreshStepAck                  MessageType = 555
	MessageType_MessageType_MoneroLiveRefreshFinalRequest             MessageType = 556
	MessageType_MessageType_MoneroLiveRefreshFinalAck                 MessageType = 557
	// EOS
	MessageType_MessageType_EosGetPublicKey    MessageType = 600
	MessageType_MessageType_EosPublicKey       MessageType = 601
	MessageType_MessageType_EosSignTx          MessageType = 602
	MessageType_MessageType_EosTxActionRequest MessageType = 603
	MessageType_MessageType_EosTxActionAck     MessageType = 604
	MessageType_MessageType_EosSignedTx        MessageType = 605
	// Binance
	MessageType_MessageType_BinanceGetAddress   MessageType = 700
	MessageType_MessageType_BinanceAddress      MessageType = 701
	MessageType_MessageType_BinanceGetPublicKey MessageType = 702
	MessageType_MessageType_BinancePublicKey    MessageType = 703
	MessageType_MessageType_BinanceSignTx       MessageType = 704
	MessageType_MessageType_BinanceTxRequest    MessageType = 705
	MessageType_MessageType_BinanceTransferMsg  MessageType = 706
	MessageType_MessageType_BinanceOrderMsg     MessageType = 707
	MessageType_MessageType_BinanceCancelMsg    MessageType = 708
	MessageType_MessageType_BinanceSignedTx     MessageType = 709
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MessageType_Initialize",
		1:   "MessageType_Ping",
		2:   "MessageType_Success",
		3:   "MessageType_Failure",
		4:   "MessageType_ChangePin",
		5:   "MessageType_WipeDevice",
		9:   "MessageType_GetEntropy",
		10:  "MessageType_Entropy",
		13:  "MessageType_LoadDevice",
		14:  "MessageType_ResetDevice",
		17:  "MessageType_Features",
		18:  "MessageType_PinMatrixRequest",
		19:  "MessageType_PinMatrixAck",
		20:  "MessageType_Cancel",
		24:  "MessageType_ClearSession",
		25:  "MessageType_ApplySettings",
		26:  "MessageType_ButtonRequest",
		27:  "MessageType_ButtonAck",
		28:  "MessageType_ApplyFlags",
		34:  "MessageType_BackupDevice",
		35:  "MessageType_EntropyRequest",
		36:  "MessageType_EntropyAck",
		41:  "MessageType_PassphraseRequest",
		42:  "MessageType_PassphraseAck",
		77:  "MessageType_PassphraseStateRequest",
		78:  "MessageType_PassphraseStateAck",
		45:  "MessageType_RecoveryDevice",
		46:  "MessageType_WordRequest",
		47:  "MessageType_WordAck",
		55:  "MessageType_GetFeatures",
		63:  "MessageType_SetU2FCounter",
		6:   "MessageType_FirmwareErase",
		7:   "MessageType_FirmwareUpload",
		8:   "MessageType_FirmwareRequest",
		32:  "MessageType_SelfTest",
		11:  "MessageType_GetPublicKey",
		12:  "MessageType_PublicKey",
		15:  "MessageType_SignTx",
		21:  "MessageType_TxRequest",
		22:  "MessageType_TxAck",
		29:  "MessageType_GetAddress",
		30:  "MessageType_Address",
		38:  "MessageType_SignMessage",
		39:  "MessageType_VerifyMessage",
		40:  "MessageType_MessageSignature",
		23:  "MessageType_CipherKeyValue",
		48:  "MessageType_CipheredKeyValue",
		53:  "MessageType_SignIdentity",
		54:  "MessageType_SignedIdentity",
		61:  "MessageType_GetECDHSessionKey",
		62:  "MessageType_ECDHSessionKey",
		71:  "MessageType_CosiCommit",
		72:  "MessageType_CosiCommitment",
		73:  "MessageType_CosiSign",
		74:  "MessageType_CosiSignature",
		100: "MessageType_DebugLinkDecision",
		101: "MessageType_DebugLinkGetState",
		102: "MessageType_DebugLinkState",
		103: "MessageType_DebugLinkStop",
		104: "MessageType_DebugLinkLog",
		110: "MessageType_DebugLinkMemoryRead",
		111: "MessageType_DebugLinkMemory",
		112: "MessageType_DebugLinkMemoryWrite",
		113: "MessageType_DebugLinkFlashErase",
		450: "MessageType_EthereumGetPublicKey",
		451: "MessageType_EthereumPublicKey",
		56:  "MessageType_EthereumGetAddress",
		57:  "MessageType_EthereumAddress",
		58:  "MessageType_EthereumSignTx",
		59:  "MessageType_EthereumTxRequest",
		60:  "MessageType_EthereumTxAck",
		64:  "MessageType_EthereumSignMessage",
		65:  "MessageType_EthereumVerifyMessage",
		66:  "MessageType_EthereumMessageSignature",
		67:  "MessageType_NEMGetAddress",
		68:  "MessageType_NEMAddress",
		69:  "MessageType_NEMSignTx",
		70:  "MessageType_NEMSignedTx",
		75:  "MessageType_NEMDecryptMessage",
		76:  "MessageType_NEMDecryptedMessage",
		114: "MessageType_LiskGetAddress",
		115: "MessageType_LiskAddress",
		116: "MessageType_LiskSignTx",
		117: "MessageType_LiskSignedTx",
		118: "MessageType_LiskSignMessage",
		119: "MessageType_LiskMessageSignature",
		120: "MessageType_LiskVerifyMessage",
		121: "MessageType_LiskGetPublicKey",
		122: "MessageType_LiskPublicKey",
		150: "MessageType_TezosGetAddress",
		151: "MessageType_TezosAddress",
		152: "MessageType_TezosSignTx",
		153: "MessageType_TezosSignedTx",
		154: "MessageType_TezosGetPublicKey",
		155: "MessageType_TezosPublicKey",
		202: "MessageType_StellarSignTx",
		203: "MessageType_StellarTxOpRequest",
		207: "MessageType_StellarGetAddress",
		208: "MessageType_StellarAddress",
		210: "MessageType_StellarCreateAccountOp",
		211: "MessageType_StellarPaymentOp",
		212: "MessageType_StellarPathPaymentOp",
		213: "MessageType_StellarManageOfferOp",
		214: "MessageType_StellarCreatePassiveOfferOp",
		215: "MessageType_StellarSetOptionsOp",
		216: "MessageType_StellarChangeTrustOp",
		217: "MessageType_StellarAllowTrustOp",
		218: "MessageType_StellarAccountMergeOp",
		220: "MessageType_StellarManageDataOp",
		221: "MessageType_StellarBumpSequenceOp",
		230: "MessageType_StellarSignedTx",
		250: "MessageType_TronGetAddress",
		251: "MessageType_TronAddress",
		252: "MessageType_TronSignTx",
		253: "MessageType_TronSignedTx",
		303: "MessageType_CardanoSignTx",
		304: "MessageType_CardanoTxRequest",
		305: "MessageType_CardanoGetPublicKey",
		306: "MessageType_CardanoPublicKey",
		307: "MessageType_CardanoGetAddress",
		308: "MessageType_CardanoAddress",
		309: "MessageType_CardanoTxAck",
		310: "MessageType_CardanoSignedTx",
		350: "MessageType_OntologyGetAddress",
		351: "MessageType_OntologyAddress",
		352: "MessageType_OntologyGetPublicKey",
		353: "MessageType_OntologyPublicKey",
		354: "MessageType_OntologySignTransfer",
		355: "MessageType_OntologySignedTransfer",
		356: "MessageType_OntologySignWithdrawOng",
		357: "MessageType_OntologySignedWithdrawOng",
		358: "MessageType_OntologySignOntIdRegister",
		359: "MessageType_OntologySignedOntIdRegister",
		360: "MessageType_OntologySignOntIdAddAttributes",
		361: "MessageType_OntologySignedOntIdAddAttributes",
		400: "MessageType_RippleGetAddress",
		401: "MessageType_RippleAddress",
		402: "MessageType_RippleSignTx",
		403: "MessageType_RippleSignedTx",
		501: "MessageType_MoneroTransactionInitRequest",
		502: "MessageType_MoneroTransactionInitAck",
		503: "MessageType_MoneroTransactionSetInputRequest",
		504: "MessageType_MoneroTransactionSetInputAck",
		505: "MessageType_MoneroTransactionInputsPermutationRequest",
		506: "MessageType_MoneroTransactionInputsPermutationAck",
		507: "MessageType_MoneroTransactionInputViniRequest",
		508: "MessageType_MoneroTransactionInputViniAck",
		509: "MessageType_MoneroTransactionAllInputsSetRequest",
		510: "MessageType_MoneroTransactionAllInputsSetAck",
		511: "MessageType_MoneroTransactionSetOutputRequest",
		512: "MessageType_MoneroTransactionSetOutputAck",
		513: "MessageType_MoneroTransactionAllOutSetRequest",
		514: "MessageType_MoneroTransactionAllOutSetAck",
		515: "MessageType_MoneroTransactionSignInputRequest",
		516: "MessageType_MoneroTransactionSignInputAck",
		517: "MessageType_MoneroTransactionFinalRequest",
		518: "MessageType_MoneroTransactionFinalAck",
		530: "MessageType_MoneroKeyImageExportInitRequest",
		531: "MessageType_MoneroKeyImageExportInitAck",
		532: "MessageType_MoneroKeyImageSyncStepRequest",
		533: "MessageType_MoneroKeyImageSyncStepAck",
		534: "MessageType_MoneroKeyImageSyncFinalRequest",
		535: "MessageType_MoneroKeyImageSyncFinalAck",
		540: "MessageType_MoneroGetAddress",
		541: "MessageType_MoneroAddress",
		542: "MessageType_MoneroGetWatchKey",
		543: "MessageType_MoneroWatchKey",
		546: "MessageType_DebugMoneroDiagRequest",
		547: "MessageType_DebugMoneroDiagAck",
		550: "MessageType_MoneroGetTxKeyRequest",
		551: "MessageType_MoneroGetTxKeyAck",
		552: "MessageType_MoneroLiveRefreshStartRequest",
		553: "MessageType_MoneroLiveRefreshStartAck",
		554: "MessageType_MoneroLiveRefreshStepRequest",
		555: "MessageType_MoneroLiveRefreshStepAck",
		556: "MessageType_MoneroLiveRefreshFinalRequest",
		557: "MessageType_MoneroLiveRefreshFinalAck",
		600: "MessageType_EosGetPublicKey",
		601: "MessageType_EosPublicKey",
		602: "MessageType_EosSignTx",
		603: "MessageType_EosTxActionRequest",
		604: "MessageType_EosTxActionAck",
		605: "MessageType_EosSignedTx",
		700: "MessageType_BinanceGetAddress",
		701: "MessageType_BinanceAddress",
		702: "MessageType_BinanceGetPublicKey",
		703: "MessageType_BinancePublicKey",
		704: "MessageType_BinanceSignTx",
		705: "MessageType_BinanceTxRequest",
		706: "MessageType_BinanceTransferMsg",
		707: "MessageType_BinanceOrderMsg",
		708: "MessageType_BinanceCancelMsg",
		709: "MessageType_BinanceSignedTx",
	}
	MessageType_value = map[string]int32{
		"MessageType_Initialize":                                0,
		"MessageType_Ping":                                      1,
		"MessageType_Success":                                   2,
		"MessageType_Failure":                                   3,
		"MessageType_ChangePin":                                 4,
		"MessageType_WipeDevice":                                5,
		"MessageType_GetEntropy":                                9,
		"MessageType_Entropy":                                   10,
		"MessageType_LoadDevice":                                13,
		"MessageType_ResetDevice":                               14,
		"MessageType_Features":                                  17,
		"MessageType_PinMatrixRequest":                          18,
		"MessageType_PinMatrixAck":                              19,
		"MessageType_Cancel":                                    20,
		"MessageType_ClearSession":                              24,
		"MessageType_ApplySettings":                             25,
		"MessageType_ButtonRequest":                             26,
		"MessageType_ButtonAck":                                 27,
		"MessageType_ApplyFlags":                                28,
		"MessageType_BackupDevice":                              34,
		"MessageType_EntropyRequest":                            35,
		"MessageType_EntropyAck":                                36,
		"MessageType_PassphraseRequest":                         41,
		"MessageType_PassphraseAck":                             42,
		"MessageType_PassphraseStateRequest":                    77,
		"MessageType_PassphraseStateAck":                        78,
		"MessageType_RecoveryDevice":                            45,
		"MessageType_WordRequest":                               46,
		"MessageType_WordAck":                                   47,
		"MessageType_GetFeatures":                               55,
		"MessageType_SetU2FCounter":                             63,
		"MessageType_FirmwareErase":                             6,
		"MessageType_FirmwareUpload":                            7,
		"MessageType_FirmwareRequest":                           8,
		"MessageType_SelfTest":                                  32,
		"MessageType_GetPublicKey":                              11,
		"MessageType_PublicKey":                                 12,
		"MessageType_SignTx":                                    15,
		"MessageType_TxRequest":                                 21,
		"MessageType_TxAck":                                     22,
		"MessageType_GetAddress":                                29,
		"MessageType_Address":                                   30,
		"MessageType_SignMessage":                               38,
		"MessageType_VerifyMessage":                             39,
		"MessageType_MessageSignature":                          40,
		"MessageType_CipherKeyValue":                            23,
		"MessageType_CipheredKeyValue":                          48,
		"MessageType_SignIdentity":                              53,
		"MessageType_SignedIdentity":                            54,
		"MessageType_GetECDHSessionKey":                         61,
		"MessageType_ECDHSessionKey":                            62,
		"MessageType_CosiCommit":                                71,
		"MessageType_CosiCommitment":                            72,
		"MessageType_CosiSign":                                  73,
		"MessageType_CosiSignature":                             74,
		"MessageType_DebugLinkDecision":                         100,
		"MessageType_DebugLinkGetState":                         101,
		"MessageType_DebugLinkState":                            102,
		"MessageType_DebugLinkStop":                             103,
		"MessageType_DebugLinkLog":                              104,
		"MessageType_DebugLinkMemoryRead":                       110,
		"MessageType_DebugLinkMemory":                           111,
		"MessageType_DebugLinkMemoryWrite":                      112,
		"MessageType_DebugLinkFlashErase":                       113,
		"MessageType_EthereumGetPublicKey":                      450,
		"MessageType_EthereumPublicKey":                         451,
		"MessageType_EthereumGetAddress":                        56,
		"MessageType_EthereumAddress":                           57,
		"MessageType_EthereumSignTx":                            58,
		"MessageType_EthereumTxRequest":                         59,
		"MessageType_EthereumTxAck":                             60,
		"MessageType_EthereumSignMessage":                       64,
		"MessageType_EthereumVerifyMessage":                     65,
		"MessageType_EthereumMessageSignature":                  66,
		"MessageType_NEMGetAddress":                             67,
		"MessageType_NEMAddress":                                68,
		"MessageType_NEMSignTx":                                 69,
		"MessageType_NEMSignedTx":                               70,
		"MessageType_NEMDecryptMessage":                         75,
		"MessageType_NEMDecryptedMessage":                       76,
		"MessageType_LiskGetAddress":                            114,
		"MessageType_LiskAddress":                               115,
		"MessageType_LiskSignTx":                                116,
		"MessageType_LiskSignedTx":                              117,
		"MessageType_LiskSignMessage":                           118,
		"MessageType_LiskMessageSignature":                      119,
		"MessageType_LiskVerifyMessage":                         120,
		"MessageType_LiskGetPublicKey":                          121,
		"MessageType_LiskPublicKey":                             122,
		"MessageType_TezosGetAddress":                           150,
		"MessageType_TezosAddress":                              151,
		"MessageType_TezosSignTx":                               152,
		"MessageType_TezosSignedTx":                             153,
		"MessageType_TezosGetPublicKey":                         154,
		"MessageType_TezosPublicKey":                            155,
		"MessageType_StellarSignTx":                             202,
		"MessageType_StellarTxOpRequest":                        203,
		"MessageType_StellarGetAddress":                         207,
		"MessageType_StellarAddress":                            208,
		"MessageType_StellarCreateAccountOp":                    210,
		"MessageType_StellarPaymentOp":                          211,
		"MessageType_StellarPathPaymentOp":                      212,
		"MessageType_StellarManageOfferOp":                      213,
		"MessageType_StellarCreatePassiveOfferOp":               214,
		"MessageType_StellarSetOptionsOp":                       215,
		"MessageType_StellarChangeTrustOp":                      216,
		"MessageType_StellarAllowTrustOp":                       217,
		"MessageType_StellarAccountMergeOp":                     218,
		"MessageType_StellarManageDataOp":                       220,
		"MessageType_StellarBumpSequenceOp":                     221,
		"MessageType_StellarSignedTx":                           230,
		"MessageType_TronGetAddress":                            250,
		"MessageType_TronAddress":                               251,
		"MessageType_TronSignTx":                                252,
		"MessageType_TronSignedTx":                              253,
		"MessageType_CardanoSignTx":                             303,
		"MessageType_CardanoTxRequest":                          304,
		"MessageType_CardanoGetPublicKey":                       305,
		"MessageType_CardanoPublicKey":                          306,
		"MessageType_CardanoGetAddress":                         307,
		"MessageType_CardanoAddress":                            308,
		"MessageType_CardanoTxAck":                              309,
		"MessageType_CardanoSignedTx":                           310,
		"MessageType_OntologyGetAddress":                        350,
		"MessageType_OntologyAddress":                           351,
		"MessageType_OntologyGetPublicKey":                      352,
		"MessageType_OntologyPublicKey":                         353,
		"MessageType_OntologySignTransfer":                      354,
		"MessageType_OntologySignedTransfer":                    355,
		"MessageType_OntologySignWithdrawOng":                   356,
		"MessageType_OntologySignedWithdrawOng":                 357,
		"MessageType_OntologySignOntIdRegister":                 358,
		"MessageType_OntologySignedOntIdRegister":               359,
		"MessageType_OntologySignOntIdAddAttributes":            360,
		"MessageType_OntologySignedOntIdAddAttributes":          361,
		"MessageType_RippleGetAddress":                          400,
		"MessageType_RippleAddress":                             401,
		"MessageType_RippleSignTx":                              402,
		"MessageType_RippleSignedTx":                            403,
		"MessageType_MoneroTransactionInitRequest":              501,
		"MessageType_MoneroTransactionInitAck":                  502,
		"MessageType_MoneroTransactionSetInputRequest":          503,
		"MessageType_MoneroTransactionSetInputAck":              504,
		"MessageType_MoneroTransactionInputsPermutationRequest": 505,
		"MessageType_MoneroTransactionInputsPermutationAck":     506,
		"MessageType_MoneroTransactionInputViniRequest":         507,
		"MessageType_MoneroTransactionInputViniAck":             508,
		"MessageType_MoneroTransactionAllInputsSetRequest":      509,
		"MessageType_MoneroTransactionAllInputsSetAck":          510,
		"MessageType_MoneroTransactionSetOutputRequest":         511,
		"MessageType_MoneroTransactionSetOutputAck":             512,
		"MessageType_MoneroTransactionAllOutSetRequest":         513,
		"MessageType_MoneroTransactionAllOutSetAck":             514,
		"MessageType_MoneroTransactionSignInputRequest":         515,
		"MessageType_MoneroTransactionSignInputAck":             516,
		"MessageType_MoneroTransactionFinalRequest":             517,
		"MessageType_MoneroTransactionFinalAck":                 518,
		"MessageType_MoneroKeyImageExportInitRequest":           530,
		"MessageType_MoneroKeyImageExportInitAck":               531,
		"MessageType_MoneroKeyImageSyncStepRequest":             532,
		"MessageType_MoneroKeyImageSyncStepAck":                 533,
		"MessageType_MoneroKeyImageSyncFinalRequest":            534,
		"MessageType_MoneroKeyImageSyncFinalAck":                535,
		"MessageType_MoneroGetAddress":                          540,
		"MessageType_MoneroAddress":                             541,
		"MessageType_MoneroGetWatchKey":                         542,
		"MessageType_MoneroWatchKey":                            543,
		"MessageType_DebugMoneroDiagRequest":                    546,
		"MessageType_DebugMoneroDiagAck":                        547,
		"MessageType_MoneroGetTxKeyRequest":                     550,
		"MessageType_MoneroGetTxKeyAck":                         551,
		"MessageType_MoneroLiveRefreshStartRequest":             552,
		"MessageType_MoneroLiveRefreshStartAck":                 553,
		"MessageType_MoneroLiveRefreshStepRequest":              554,
		"MessageType_MoneroLiveRefreshStepAck":                  555,
		"MessageType_MoneroLiveRefreshFinalRequest":             556,
		"MessageType_MoneroLiveRefreshFinalAck":                 557,
		"MessageType_EosGetPublicKey":                           600,
		"MessageType_EosPublicKey":                              601,
		"MessageType_EosSignTx":                                 602,
		"MessageType_EosTxActionRequest":                        603,
		"MessageType_EosTxActionAck":                            604,
		"MessageType_EosSignedTx":                               605,
		"MessageType_BinanceGetAddress":                         700,
		"MessageType_BinanceAddress":                            701,
		"MessageType_BinanceGetPublicKey":                       702,
		"MessageType_BinancePublicKey":                          703,
		"MessageType_BinanceSignTx":                             704,
		"MessageType_BinanceTxRequest":                          705,
		"MessageType_BinanceTransferMsg":                        706,
		"MessageType_BinanceOrderMsg":                           707,
		"MessageType_BinanceCancelMsg":                          708,
		"MessageType_BinanceSignedTx":                           709,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MessageType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MessageType(num)
	return nil
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

var file_messages_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "hw.trezor.messages.wire_in",
		Tag:           "varint,50002,opt,name=wire_in",
		Filename:      "messages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "hw.trezor.messages.wire_out",
		Tag:           "varint,50003,opt,name=wire_out",
		Filename:      "messages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "hw.trezor.messages.wire_debug_in",
		Tag:           "varint,50004,opt,name=wire_debug_in",
		Filename:      "messages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "hw.trezor.messages.wire_debug_out",
		Tag:           "varint,50005,opt,name=wire_debug_out",
		Filename:      "messages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50006,
		Name:          "hw.trezor.messages.wire_tiny",
		Tag:           "varint,50006,opt,name=wire_tiny",
		Filename:      "messages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50007,
		Name:          "hw.trezor.messages.wire_bootloader",
		Tag:           "varint,50007,opt,name=wire_bootloader",
		Filename:      "messages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50008,
		Name:          "hw.trezor.messages.wire_no_fsm",
		Tag:           "varint,50008,opt,name=wire_no_fsm",
		Filename:      "messages.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional bool wire_in = 50002;
	E_WireIn = &file_messages_proto_extTypes[0] // message can be transmitted via wire from PC to TREZOR
	// optional bool wire_out = 50003;
	E_WireOut = &file_messages_proto_extTypes[1] // message can be transmitted via wire from TREZOR to PC
	// optional bool wire_debug_in = 50004;
	E_WireDebugIn = &file_messages_proto_extTypes[2] // message can be transmitted via debug wire from PC to TREZOR
	// optional bool wire_debug_out = 50005;
	E_WireDebugOut = &file_messages_proto_extTypes[3] // message can be transmitted via debug wire from TREZOR to PC
	// optional bool wire_tiny = 50006;
	E_WireTiny = &file_messages_proto_extTypes[4] // message is handled by TREZOR when the USB stack is in tiny mode
	// optional bool wire_bootloader = 50007;
	E_WireBootloader = &file_messages_proto_extTypes[5] // message is only handled by TREZOR Bootloader
	// optional bool wire_no_fsm = 50008;
	E_WireNoFsm = &file_messages_proto_extTypes[6] // message is not handled by TREZOR unless the USB stack is in tiny mode
)

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x12hw.trezor.messages\x1a google/protobuf/descriptor.proto*\xb9?\n" +
	"\vMessageType\x12$\n" +
	"\x16MessageType_Initialize\x10\x00\x1a\b\x90\xb5\x18\x01\xb0\xb5\x18\x01\x12\x1a\n" +
	"\x10MessageType_Ping\x10\x01\x1a\x04\x90\xb5\x18\x01\x12\x1d\n" +
	"\x13MessageType_Success\x10\x02\x1a\x04\x98\xb5\x18\x01\x12\x1d\n" +
	"\x13MessageType_Failure\x10\x03\x1a\x04\x98\xb5\x18\x01\x12\x1f\n" +
	"\x15MessageType_ChangePin\x10\x04\x1a\x04\x90\xb5\x18\x01\x12 \n" +
	"\x16MessageType_WipeDevice\x10\x05\x1a\x04\x90\xb5\x18\x01\x12 \n" +
	"\x16MessageType_GetEntropy\x10\t\x1a\x04\x90\xb5\x18\x01\x12\x1d\n" +
	"\x13MessageType_Entropy\x10\n" +
	"\x1a\x04\x98\xb5\x18\x01\x12 \n" +
	"\x16MessageType_LoadDevice\x10\r\x1a\x04\x90\xb5\x18\x01\x12!\n" +
	"\x17MessageType_ResetDevice\x10\x0e\x1a\x04\x90\xb5\x18\x01\x12\x1e\n" +
	"\x14MessageType_Features\x10\x11\x1a\x04\x98\xb5\x18\x01\x12&\n" +
	"\x1cMessageType_PinMatrixRequest\x10\x12\x1a\x04\x98\xb5\x18\x01\x12*\n" +
	"\x18MessageType_PinMatrixAck\x10\x13\x1a\f\x90\xb5\x18\x01\xb0\xb5\x18\x01\xc0\xb5\x18\x01\x12 \n" +
	"\x12MessageType_Cancel\x10\x14\x1a\b\x90\xb5\x18\x01\xb0\xb5\x18\x01\x12\"\n" +
	"\x18MessageType_ClearSession\x10\x18\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x19MessageType_ApplySettings\x10\x19\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x19MessageType_ButtonRequest\x10\x1a\x1a\x04\x98\xb5\x18\x01\x12'\n" +
	"\x15MessageType_ButtonAck\x10\x1b\x1a\f\x90\xb5\x18\x01\xb0\xb5\x18\x01\xc0\xb5\x18\x01\x12 \n" +
	"\x16MessageType_ApplyFlags\x10\x1c\x1a\x04\x90\xb5\x18\x01\x12\"\n" +
	"\x18MessageType_BackupDevice\x10\"\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_EntropyRequest\x10#\x1a\x04\x98\xb5\x18\x01\x12 \n" +
	"\x16MessageType_EntropyAck\x10$\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1dMessageType_PassphraseRequest\x10)\x1a\x04\x98\xb5\x18\x01\x12+\n" +
	"\x19MessageType_PassphraseAck\x10*\x1a\f\x90\xb5\x18\x01\xb0\xb5\x18\x01\xc0\xb5\x18\x01\x12,\n" +
	"\"MessageType_PassphraseStateRequest\x10M\x1a\x04\x98\xb5\x18\x01\x120\n" +
	"\x1eMessageType_PassphraseStateAck\x10N\x1a\f\x90\xb5\x18\x01\xb0\xb5\x18\x01\xc0\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_RecoveryDevice\x10-\x1a\x04\x90\xb5\x18\x01\x12!\n" +
	"\x17MessageType_WordRequest\x10.\x1a\x04\x98\xb5\x18\x01\x12\x1d\n" +
	"\x13MessageType_WordAck\x10/\x1a\x04\x90\xb5\x18\x01\x12!\n" +
	"\x17MessageType_GetFeatures\x107\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x19MessageType_SetU2FCounter\x10?\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x19MessageType_FirmwareErase\x10\x06\x1a\b\x90\xb5\x18\x01\xb8\xb5\x18\x01\x12(\n" +
	"\x1aMessageType_FirmwareUpload\x10\a\x1a\b\x90\xb5\x18\x01\xb8\xb5\x18\x01\x12)\n" +
	"\x1bMessageType_FirmwareRequest\x10\b\x1a\b\x98\xb5\x18\x01\xb8\xb5\x18\x01\x12\"\n" +
	"\x14MessageType_SelfTest\x10 \x1a\b\x90\xb5\x18\x01\xb8\xb5\x18\x01\x12\"\n" +
	"\x18MessageType_GetPublicKey\x10\v\x1a\x04\x90\xb5\x18\x01\x12\x1f\n" +
	"\x15MessageType_PublicKey\x10\f\x1a\x04\x98\xb5\x18\x01\x12\x1c\n" +
	"\x12MessageType_SignTx\x10\x0f\x1a\x04\x90\xb5\x18\x01\x12\x1f\n" +
	"\x15MessageType_TxRequest\x10\x15\x1a\x04\x98\xb5\x18\x01\x12\x1b\n" +
	"\x11MessageType_TxAck\x10\x16\x1a\x04\x90\xb5\x18\x01\x12 \n" +
	"\x16MessageType_GetAddress\x10\x1d\x1a\x04\x90\xb5\x18\x01\x12\x1d\n" +
	"\x13MessageType_Address\x10\x1e\x1a\x04\x98\xb5\x18\x01\x12!\n" +
	"\x17MessageType_SignMessage\x10&\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x19MessageType_VerifyMessage\x10'\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1cMessageType_MessageSignature\x10(\x1a\x04\x98\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_CipherKeyValue\x10\x17\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1cMessageType_CipheredKeyValue\x100\x1a\x04\x98\xb5\x18\x01\x12\"\n" +
	"\x18MessageType_SignIdentity\x105\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_SignedIdentity\x106\x1a\x04\x98\xb5\x18\x01\x12'\n" +
	"\x1dMessageType_GetECDHSessionKey\x10=\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_ECDHSessionKey\x10>\x1a\x04\x98\xb5\x18\x01\x12 \n" +
	"\x16MessageType_CosiCommit\x10G\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_CosiCommitment\x10H\x1a\x04\x98\xb5\x18\x01\x12\x1e\n" +
	"\x14MessageType_CosiSign\x10I\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x19MessageType_CosiSignature\x10J\x1a\x04\x98\xb5\x18\x01\x12/\n" +
	"\x1dMessageType_DebugLinkDecision\x10d\x1a\f\xa0\xb5\x18\x01\xb0\xb5\x18\x01\xc0\xb5\x18\x01\x12+\n" +
	"\x1dMessageType_DebugLinkGetState\x10e\x1a\b\xa0\xb5\x18\x01\xb0\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_DebugLinkState\x10f\x1a\x04\xa8\xb5\x18\x01\x12#\n" +
	"\x19MessageType_DebugLinkStop\x10g\x1a\x04\xa0\xb5\x18\x01\x12\"\n" +
	"\x18MessageType_DebugLinkLog\x10h\x1a\x04\xa8\xb5\x18\x01\x12)\n" +
	"\x1fMessageType_DebugLinkMemoryRead\x10n\x1a\x04\xa0\xb5\x18\x01\x12%\n" +
	"\x1bMessageType_DebugLinkMemory\x10o\x1a\x04\xa8\xb5\x18\x01\x12*\n" +
	" MessageType_DebugLinkMemoryWrite\x10p\x1a\x04\xa0\xb5\x18\x01\x12)\n" +
	"\x1fMessageType_DebugLinkFlashErase\x10q\x1a\x04\xa0\xb5\x18\x01\x12+\n" +
	" MessageType_EthereumGetPublicKey\x10\xc2\x03\x1a\x04\x90\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_EthereumPublicKey\x10\xc3\x03\x1a\x04\x98\xb5\x18\x01\x12(\n" +
	"\x1eMessageType_EthereumGetAddress\x108\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1bMessageType_EthereumAddress\x109\x1a\x04\x98\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_EthereumSignTx\x10:\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1dMessageType_EthereumTxRequest\x10;\x1a\x04\x98\xb5\x18\x01\x12#\n" +
	"\x19MessageType_EthereumTxAck\x10<\x1a\x04\x90\xb5\x18\x01\x12)\n" +
	"\x1fMessageType_EthereumSignMessage\x10@\x1a\x04\x90\xb5\x18\x01\x12+\n" +
	"!MessageType_EthereumVerifyMessage\x10A\x1a\x04\x90\xb5\x18\x01\x12.\n" +
	"$MessageType_EthereumMessageSignature\x10B\x1a\x04\x98\xb5\x18\x01\x12#\n" +
	"\x19MessageType_NEMGetAddress\x10C\x1a\x04\x90\xb5\x18\x01\x12 \n" +
	"\x16MessageType_NEMAddress\x10D\x1a\x04\x98\xb5\x18\x01\x12\x1f\n" +
	"\x15MessageType_NEMSignTx\x10E\x1a\x04\x90\xb5\x18\x01\x12!\n" +
	"\x17MessageType_NEMSignedTx\x10F\x1a\x04\x98\xb5\x18\x01\x12'\n" +
	"\x1dMessageType_NEMDecryptMessage\x10K\x1a\x04\x90\xb5\x18\x01\x12)\n" +
	"\x1fMessageType_NEMDecryptedMessage\x10L\x1a\x04\x98\xb5\x18\x01\x12$\n" +
	"\x1aMessageType_LiskGetAddress\x10r\x1a\x04\x90\xb5\x18\x01\x12!\n" +
	"\x17MessageType_LiskAddress\x10s\x1a\x04\x98\xb5\x18\x01\x12 \n" +
	"\x16MessageType_LiskSignTx\x10t\x1a\x04\x90\xb5\x18\x01\x12\"\n" +
	"\x18MessageType_LiskSignedTx\x10u\x1a\x04\x98\xb5\x18\x01\x12%\n" +
	"\x1bMessageType_LiskSignMessage\x10v\x1a\x04\x90\xb5\x18\x01\x12*\n" +
	" MessageType_LiskMessageSignature\x10w\x1a\x04\x98\xb5\x18\x01\x12'\n" +
	"\x1dMessageType_LiskVerifyMessage\x10x\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1cMessageType_LiskGetPublicKey\x10y\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x19MessageType_LiskPublicKey\x10z\x1a\x04\x98\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_TezosGetAddress\x10\x96\x01\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x18MessageType_TezosAddress\x10\x97\x01\x1a\x04\x98\xb5\x18\x01\x12\"\n" +
	"\x17MessageType_TezosSignTx\x10\x98\x01\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x19MessageType_TezosSignedTx\x10\x99\x01\x1a\x04\x98\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_TezosGetPublicKey\x10\x9a\x01\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_TezosPublicKey\x10\x9b\x01\x1a\x04\x98\xb5\x18\x01\x12$\n" +
	"\x19MessageType_StellarSignTx\x10\xca\x01\x1a\x04\x90\xb5\x18\x01\x12)\n" +
	"\x1eMessageType_StellarTxOpRequest\x10\xcb\x01\x1a\x04\x98\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_StellarGetAddress\x10\xcf\x01\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_StellarAddress\x10\xd0\x01\x1a\x04\x98\xb5\x18\x01\x12-\n" +
	"\"MessageType_StellarCreateAccountOp\x10\xd2\x01\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_StellarPaymentOp\x10\xd3\x01\x1a\x04\x90\xb5\x18\x01\x12+\n" +
	" MessageType_StellarPathPaymentOp\x10\xd4\x01\x1a\x04\x90\xb5\x18\x01\x12+\n" +
	" MessageType_StellarManageOfferOp\x10\xd5\x01\x1a\x04\x90\xb5\x18\x01\x122\n" +
	"'MessageType_StellarCreatePassiveOfferOp\x10\xd6\x01\x1a\x04\x90\xb5\x18\x01\x12*\n" +
	"\x1fMessageType_StellarSetOptionsOp\x10\xd7\x01\x1a\x04\x90\xb5\x18\x01\x12+\n" +
	" MessageType_StellarChangeTrustOp\x10\xd8\x01\x1a\x04\x90\xb5\x18\x01\x12*\n" +
	"\x1fMessageType_StellarAllowTrustOp\x10\xd9\x01\x1a\x04\x90\xb5\x18\x01\x12,\n" +
	"!MessageType_StellarAccountMergeOp\x10\xda\x01\x1a\x04\x90\xb5\x18\x01\x12*\n" +
	"\x1fMessageType_StellarManageDataOp\x10\xdc\x01\x1a\x04\x90\xb5\x18\x01\x12,\n" +
	"!MessageType_StellarBumpSequenceOp\x10\xdd\x01\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_StellarSignedTx\x10\xe6\x01\x1a\x04\x98\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_TronGetAddress\x10\xfa\x01\x1a\x04\x90\xb5\x18\x01\x12\"\n" +
	"\x17MessageType_TronAddress\x10\xfb\x01\x1a\x04\x98\xb5\x18\x01\x12!\n" +
	"\x16MessageType_TronSignTx\x10\xfc\x01\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x18MessageType_TronSignedTx\x10\xfd\x01\x1a\x04\x98\xb5\x18\x01\x12$\n" +
	"\x19MessageType_CardanoSignTx\x10\xaf\x02\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_CardanoTxRequest\x10\xb0\x02\x1a\x04\x98\xb5\x18\x01\x12*\n" +
	"\x1fMessageType_CardanoGetPublicKey\x10\xb1\x02\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_CardanoPublicKey\x10\xb2\x02\x1a\x04\x98\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_CardanoGetAddress\x10\xb3\x02\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_CardanoAddress\x10\xb4\x02\x1a\x04\x98\xb5\x18\x01\x12#\n" +
	"\x18MessageType_CardanoTxAck\x10\xb5\x02\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_CardanoSignedTx\x10\xb6\x02\x1a\x04\x98\xb5\x18\x01\x12)\n" +
	"\x1eMessageType_OntologyGetAddress\x10\xde\x02\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_OntologyAddress\x10\xdf\x02\x1a\x04\x98\xb5\x18\x01\x12+\n" +
	" MessageType_OntologyGetPublicKey\x10\xe0\x02\x1a\x04\x90\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_OntologyPublicKey\x10\xe1\x02\x1a\x04\x98\xb5\x18\x01\x12+\n" +
	" MessageType_OntologySignTransfer\x10\xe2\x02\x1a\x04\x90\xb5\x18\x01\x12-\n" +
	"\"MessageType_OntologySignedTransfer\x10\xe3\x02\x1a\x04\x98\xb5\x18\x01\x12.\n" +
	"#MessageType_OntologySignWithdrawOng\x10\xe4\x02\x1a\x04\x90\xb5\x18\x01\x120\n" +
	"%MessageType_OntologySignedWithdrawOng\x10\xe5\x02\x1a\x04\x98\xb5\x18\x01\x120\n" +
	"%MessageType_OntologySignOntIdRegister\x10\xe6\x02\x1a\x04\x90\xb5\x18\x01\x122\n" +
	"'MessageType_OntologySignedOntIdRegister\x10\xe7\x02\x1a\x04\x98\xb5\x18\x01\x125\n" +
	"*MessageType_OntologySignOntIdAddAttributes\x10\xe8\x02\x1a\x04\x90\xb5\x18\x01\x127\n" +
	",MessageType_OntologySignedOntIdAddAttributes\x10\xe9\x02\x1a\x04\x98\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_RippleGetAddress\x10\x90\x03\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x19MessageType_RippleAddress\x10\x91\x03\x1a\x04\x98\xb5\x18\x01\x12#\n" +
	"\x18MessageType_RippleSignTx\x10\x92\x03\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_RippleSignedTx\x10\x93\x03\x1a\x04\x90\xb5\x18\x01\x123\n" +
	"(MessageType_MoneroTransactionInitRequest\x10\xf5\x03\x1a\x04\x98\xb5\x18\x01\x12/\n" +
	"$MessageType_MoneroTransactionInitAck\x10\xf6\x03\x1a\x04\x98\xb5\x18\x01\x127\n" +
	",MessageType_MoneroTransactionSetInputRequest\x10\xf7\x03\x1a\x04\x98\xb5\x18\x01\x123\n" +
	"(MessageType_MoneroTransactionSetInputAck\x10\xf8\x03\x1a\x04\x98\xb5\x18\x01\x12@\n" +
	"5MessageType_MoneroTransactionInputsPermutationRequest\x10\xf9\x03\x1a\x04\x98\xb5\x18\x01\x12<\n" +
	"1MessageType_MoneroTransactionInputsPermutationAck\x10\xfa\x03\x1a\x04\x98\xb5\x18\x01\x128\n" +
	"-MessageType_MoneroTransactionInputViniRequest\x10\xfb\x03\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroTransactionInputViniAck\x10\xfc\x03\x1a\x04\x98\xb5\x18\x01\x12;\n" +
	"0MessageType_MoneroTransactionAllInputsSetRequest\x10\xfd\x03\x1a\x04\x98\xb5\x18\x01\x127\n" +
	",MessageType_MoneroTransactionAllInputsSetAck\x10\xfe\x03\x1a\x04\x98\xb5\x18\x01\x128\n" +
	"-MessageType_MoneroTransactionSetOutputRequest\x10\xff\x03\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroTransactionSetOutputAck\x10\x80\x04\x1a\x04\x98\xb5\x18\x01\x128\n" +
	"-MessageType_MoneroTransactionAllOutSetRequest\x10\x81\x04\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroTransactionAllOutSetAck\x10\x82\x04\x1a\x04\x98\xb5\x18\x01\x128\n" +
	"-MessageType_MoneroTransactionSignInputRequest\x10\x83\x04\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroTransactionSignInputAck\x10\x84\x04\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroTransactionFinalRequest\x10\x85\x04\x1a\x04\x98\xb5\x18\x01\x120\n" +
	"%MessageType_MoneroTransactionFinalAck\x10\x86\x04\x1a\x04\x98\xb5\x18\x01\x126\n" +
	"+MessageType_MoneroKeyImageExportInitRequest\x10\x92\x04\x1a\x04\x98\xb5\x18\x01\x122\n" +
	"'MessageType_MoneroKeyImageExportInitAck\x10\x93\x04\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroKeyImageSyncStepRequest\x10\x94\x04\x1a\x04\x98\xb5\x18\x01\x120\n" +
	"%MessageType_MoneroKeyImageSyncStepAck\x10\x95\x04\x1a\x04\x98\xb5\x18\x01\x125\n" +
	"*MessageType_MoneroKeyImageSyncFinalRequest\x10\x96\x04\x1a\x04\x98\xb5\x18\x01\x121\n" +
	"&MessageType_MoneroKeyImageSyncFinalAck\x10\x97\x04\x1a\x04\x98\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_MoneroGetAddress\x10\x9c\x04\x1a\x04\x90\xb5\x18\x01\x12$\n" +
	"\x19MessageType_MoneroAddress\x10\x9d\x04\x1a\x04\x98\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_MoneroGetWatchKey\x10\x9e\x04\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_MoneroWatchKey\x10\x9f\x04\x1a\x04\x98\xb5\x18\x01\x12-\n" +
	"\"MessageType_DebugMoneroDiagRequest\x10\xa2\x04\x1a\x04\x90\xb5\x18\x01\x12)\n" +
	"\x1eMessageType_DebugMoneroDiagAck\x10\xa3\x04\x1a\x04\x98\xb5\x18\x01\x12,\n" +
	"!MessageType_MoneroGetTxKeyRequest\x10\xa6\x04\x1a\x04\x90\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_MoneroGetTxKeyAck\x10\xa7\x04\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroLiveRefreshStartRequest\x10\xa8\x04\x1a\x04\x90\xb5\x18\x01\x120\n" +
	"%MessageType_MoneroLiveRefreshStartAck\x10\xa9\x04\x1a\x04\x98\xb5\x18\x01\x123\n" +
	"(MessageType_MoneroLiveRefreshStepRequest\x10\xaa\x04\x1a\x04\x90\xb5\x18\x01\x12/\n" +
	"$MessageType_MoneroLiveRefreshStepAck\x10\xab\x04\x1a\x04\x98\xb5\x18\x01\x124\n" +
	")MessageType_MoneroLiveRefreshFinalRequest\x10\xac\x04\x1a\x04\x90\xb5\x18\x01\x120\n" +
	"%MessageType_MoneroLiveRefreshFinalAck\x10\xad\x04\x1a\x04\x98\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_EosGetPublicKey\x10\xd8\x04\x1a\x04\x90\xb5\x18\x01\x12#\n" +
	"\x18MessageType_EosPublicKey\x10\xd9\x04\x1a\x04\x98\xb5\x18\x01\x12 \n" +
	"\x15MessageType_EosSignTx\x10\xda\x04\x1a\x04\x90\xb5\x18\x01\x12)\n" +
	"\x1eMessageType_EosTxActionRequest\x10\xdb\x04\x1a\x04\x98\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_EosTxActionAck\x10\xdc\x04\x1a\x04\x90\xb5\x18\x01\x12\"\n" +
	"\x17MessageType_EosSignedTx\x10\xdd\x04\x1a\x04\x98\xb5\x18\x01\x12(\n" +
	"\x1dMessageType_BinanceGetAddress\x10\xbc\x05\x1a\x04\x90\xb5\x18\x01\x12%\n" +
	"\x1aMessageType_BinanceAddress\x10\xbd\x05\x1a\x04\x98\xb5\x18\x01\x12*\n" +
	"\x1fMessageType_BinanceGetPublicKey\x10\xbe\x05\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_BinancePublicKey\x10\xbf\x05\x1a\x04\x98\xb5\x18\x01\x12$\n" +
	"\x19MessageType_BinanceSignTx\x10\xc0\x05\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_BinanceTxRequest\x10\xc1\x05\x1a\x04\x98\xb5\x18\x01\x12)\n" +
	"\x1eMessageType_BinanceTransferMsg\x10\xc2\x05\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_BinanceOrderMsg\x10\xc3\x05\x1a\x04\x90\xb5\x18\x01\x12'\n" +
	"\x1cMessageType_BinanceCancelMsg\x10\xc4\x05\x1a\x04\x90\xb5\x18\x01\x12&\n" +
	"\x1bMessageType_BinanceSignedTx\x10\xc5\x05\x1a\x04\x98\xb5\x18\x01:<\n" +
	"\awire_in\x12!.google.protobuf.EnumValueOptions\x18҆\x03 \x01(\bR\x06wireIn:>\n" +
	"\bwire_out\x12!.google.protobuf.EnumValueOptions\x18ӆ\x03 \x01(\bR\awireOut:G\n" +
	"\rwire_debug_in\x12!.google.protobuf.EnumValueOptions\x18Ԇ\x03 \x01(\bR\vwireDebugIn:I\n" +
	"\x0ewire_debug_out\x12!.google.protobuf.EnumValueOptions\x18Ն\x03 \x01(\bR\fwireDebugOut:@\n" +
	"\twire_tiny\x12!.google.protobuf.EnumValueOptions\x18ֆ\x03 \x01(\bR\bwireTiny:L\n" +
	"\x0fwire_bootloader\x12!.google.protobuf.EnumValueOptions\x18׆\x03 \x01(\bR\x0ewireBootloader:C\n" +
	"\vwire_no_fsm\x12!.google.protobuf.EnumValueOptions\x18؆\x03 \x01(\bR\twireNoFsmBo\n" +
	"#com.satoshilabs.trezor.lib.protobufB\rTrezorMessageZ9github.com/ethereum/go-ethereum/accounts/usbwallet/trezor"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),                      // 0: hw.trezor.messages.MessageType
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_messages_proto_depIdxs = []int32{
	1, // 0: hw.trezor.messages.wire_in:extendee -> google.protobuf.EnumValueOptions
	1, // 1: hw.trezor.messages.wire_out:extendee -> google.protobuf.EnumValueOptions
	1, // 2: hw.trezor.messages.wire_debug_in:extendee -> google.protobuf.EnumValueOptions
	1, // 3: hw.trezor.messages.wire_debug_out:extendee -> google.protobuf.EnumValueOptions
	1, // 4: hw.trezor.messages.wire_tiny:extendee -> google.protobuf.EnumValueOptions
	1, // 5: hw.trezor.messages.wire_bootloader:extendee -> google.protobuf.EnumValueOptions
	1, // 6: hw.trezor.messages.wire_no_fsm:extendee -> google.protobuf.EnumValueOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	0, // [0:7] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		ExtensionInfos:    file_messages_proto_extTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
